title: Xvfan Dong's Homepage
page-top-title: Xvfan Dong
top-section-bg-text: Applied Statistics
home-subtitle: Xvfan Dong&ensp;|&ensp;董旭帆
copyright-text: '&copy; Tian Shi 2023-2025. All Rights Reserved.'
